swagger: "2.0"
info:
  version: "0.0.1"
  title: Grape API
host: localhost:3000
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /auth:
    x-swagger-router-controller: auth/auth.controller
    post:
      description: 서비스 자체 계정 로그인
      parameters:
        - name: id
          in: formData
          description: ID
          required: true
          type: string
        - name: pw
          in: formData
          description: 비밀번호
          required: true
          type: string
      responses:
        200:
          description: 로그인 성공
          examples:
            application/json: {
              accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlkZW50aXR5IjoiYSIsInR5cGUiOiJhY2Nlc3MiLCJleHAiOjE1NDA1NTc0NDYsImp0aSI6ImJiN2M3MjJmLTZkZjMtNDljYy1iZTk5LWRkMjMzNDU1NDRjZSIsIm5iZiI6MTUwOTAyMTQ0NiwiaWF0IjoxNTA5MDIxNDQ2fQ.wmytxSuQlH-KjhxO2EzrIioWHWgEnyiqWpRBwWuM15M,
              refreshToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MTM5MDQ3NjMsImlkZW50aXR5IjoibmlsIiwiZnJlc2giOmZhbHNlLCJqdGkiOiI1Yzg1ZDAxNy1lYjIwLTRmYjgtYmVhYi1iYmYyZTQyY2NlYmYiLCJuYmYiOjE1MTM2NDU1NjMsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE1MTM2NDU1NjN9.075C0_-b-oqSWc-jz7G35y00erRVntpcqN9uMIAnvfI
            }
        401:
          description: 로그인 실패(알맞지 않은 ID/PW)
  /refresh:
    post:
      description: JWT access token refresh
      parameters:
        - name: Authorization
          in: header
          description: Refresh token
          required: true
          type: string
      responses:
        200:
          description: Token refresh 성공, access token 응답
          examples:
            application/json: {
              accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlkZW50aXR5IjoiYSIsInR5cGUiOiJhY2Nlc3MiLCJleHAiOjE1NDA1NTc0NDYsImp0aSI6ImJiN2M3MjJmLTZkZjMtNDljYy1iZTk5LWRkMjMzNDU1NDRjZSIsIm5iZiI6MTUwOTAyMTQ0NiwiaWF0IjoxNTA5MDIxNDQ2fQ.wmytxSuQlH-KjhxO2EzrIioWHWgEnyiqWpRBwWuM15M
            }
        205:
          description: 해당 refresh token이 발생한 로그인 이후로, 비밀번호가 1번 이상 변경되어 재로그인 필요
        401:
          description: Refresh token이 만료됨
        422:
          description: Refresh token을 해석할 수 없음