# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.5

    working_directory: ~/repo/

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-python-requirements-{{ checksum "Server/requirements.txt" }}

      - run:
          command: |
            cd Server/
            pip3 install virtualenv
            virtualenv -p python3 .venv
            . .venv/bin/activate
            pip3 install -r requirements.txt
      
      - save_cache:
          key: v1-python-requirements-{{ checksum "Server/requirements.txt" }}
          paths:
            - "Server/.venv"
      
      - run:
          command: |
            cd Server/
            . .venv/bin/activate
            python3 -m "nose" tests/__init__.py
