# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.5

    working_directory: ~/repo/Server/

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - deps1-{{ .Brancch }}-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found

      - run:
        command: |
          pip3 install virtualenv
          virtualenv -p python3 .venv
          . .venv/bin/activate
          pip3 install -r requirements.txt

      - run: python3 -m "nose" tests/__init__.py
